version: '2.3'

services:
  app:
    build: .
    container_name: Rick_Masters
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/DB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"


  db:
    image: 'postgres:13.3'
    container_name: db
    environment:
      - POSTGRES_DB=DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"